module.exports = {
    extends: ["eslint:recommended"],
    rules: {
        "curly": ["error", "all"],
        "default-case-last": "error",
        "eqeqeq": ["error", "always"],
        "lines-between-class-members": "off",
        "new-cap": "error",
        "no-console": process.env.NODE_ENV === "production" ? "error" : "off",
        "no-debugger": process.env.NODE_ENV === "production" ? "error" : "off",
        "no-duplicate-imports": "off",
        "no-empty": ["error", {allowEmptyCatch: true}],
        "no-restricted-imports": ["error", {patterns: ["..(?:/*)?"]}],
        "no-unused-vars": "off",
        "object-shorthand": "error",
        "padding-line-between-statements": "off",
        "prefer-template": "error",
        "quotes": ["error", "double", {avoidEscape: true, allowTemplateLiterals: false}],
    },
};
